//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guest
    {
        public int ID { get; set; }
        public string GuestID { get; set; }
        public string GuestName { get; set; }
        public string GuestPhone { get; set; }
        public string GuestEmail { get; set; }
        public Nullable<int> GuestSex { get; set; }
        public string GuestAddress { get; set; }
        public Nullable<System.DateTime> GuestBirthday { get; set; }
        public string UserID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
