//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ID { get; set; }
        public string ProductID { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> ProductWeight { get; set; }
        public string ProductTrademark { get; set; }
        public Nullable<int> ProductPrice { get; set; }
        public Nullable<int> ProductPromotionPrice { get; set; }
        public string ProductDescription { get; set; }
        public Nullable<int> WarrantyPeriod { get; set; }
        public Nullable<int> CateProductID { get; set; }
    }
}
