//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestFromGuest
    {
        public int ID { get; set; }
        public string ReqFrmGueID { get; set; }
        public string GuestID { get; set; }
        public string UserID { get; set; }
        public Nullable<int> RequestID { get; set; }
        public string Description { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string GuestName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
