//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        public int ID { get; set; }
        public string StoreID { get; set; }
        public string StoreName { get; set; }
        public string StoreAddress { get; set; }
        public string StorePhone { get; set; }
        public string StoreEmail { get; set; }
        public string StoreDetail { get; set; }
        public string UserID { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string ImgSrc { get; set; }
        public string PermissionID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
